apiVersion: v1
kind: Pod
metadata:
  name: pod-operator
  namespace: default
spec:
  containers:
  - name: affinity-operator-pod
    image: nginx:latest
    ports:
    - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "app"
            operator: Exists 
