apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.config: | 
    "
    server{
      listen 80;

      location / {

        root /usr/share/nginx;
         index index.html index.htm;

     }

     }
    "
