apiVersion: apps/v1 
kind: Deployment
metadata:
  name: php-app
  namespace: prod-ns
  labels:
    env: prod 
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod 
  template:
    metadata:
      name: php-app
      labels:
        env: prod 
    spec:
      containers:
      - name: php-app
        image: amansingh12/shopping_page:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80 
          initialDelaySeconds: 10  # wait for the 10 sec after the pod start
          periodSeconds: 5 #check every 5sec
          failureThreshold: 3 # restart it it fail 3 time in a row



---

apiVersion: v1
kind: Service
metadata:
  name: php-app-service
  namespace: prod-ns
spec:
  selector:
    env: prod 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort

