apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    app: web
  namespace: default
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: nginx
      app: web
  template:
    metadata:
      labels:
        app: nginx
        app: web
    spec:
      containers:
      - name: nginx-pod
        image: nginx:latest
        ports:
        - containerPort: 80
