apiVersion: autoscaling/v1
kind: HorizontalPodAutoScaler
metadata:
  name: hpa-node-app
  namespace: prod-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-app-deploy
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60 
