apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  namespace: default
spec:
  initContainers:
  - name: init-pod
    image: busybox:latest
    command: ["sh","-c","echo 'Hello guys welcome to the init-container' > /data/index.html"]
    volumeMounts:
    - name: shared-data
      mountPath: "/data"
  containers:
  - name: pod-nginx
    image: nginx:latest 
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: "/usr/share/nginx/html"

  volumes:
  - name: shared-data
    emptyDir: {}
