apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange-prod-ns
  namespace: prod-ns
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "250m"
      memory: "256Mi"
    type: Container
