apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-pod
  namespace: default
spec:
  containers:
  - name: nginx-affinity
    image: nginx:latest
    ports:
      - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "Env"
            operator: In
            values:
            - prod


