apiVersion: v1
kind: Pod
metadata:
  name: postgress-db
  namespace: default
spec:
  containers: 
  - name: postgress-db
    image: postgres:latest
    ports:
    - containerPort: 5432
    envFrom:
    - configMapRef:
        name:  postgress-configmap
    - secretRef:
        name: postgress-secret
    resources:
      limits:
        cpu: "500m"
        memory: "500Mi"
      requests:
        cpu: "200m"
        memory: "256Mi"
    volumeMounts:
    - name: shared-volume
      mountPath: /var/lib/postgresql/data
  volumes:
  - name: shared-volume
    emptyDir: {}



