apiVersion: v1
kind: Pod
metadata:
  name: pod-dev
  namespace: default
spec:
  containers:
  - name: pod-dev
    image: nginx:latest
    ports:
    - containerPort: 80
  nodeSelector:
    app: node-2
