apiVersion: v1
kind: Pod
metadata:
  name: limit-pod
  namespace: prod-ns 
spec:
  containers:
  - name: limit-pod
    image: nginx:latest 
    ports:
    - containerPort: 80
    resources: 
      limits:
        cpu: "500m"
        memory: "500Mi"
      requests:
        cpu: "200m"
        memory: "256Mi"
