apiVersion: v1
kind: Secret
metadata:
  name: postgress-secret
  namespace: default 
type: Opaque
stringData:
  POSTGRES_USER: bXl1c2Vy             # POSTGRES_USER
  POSTGRES_PASSWORD:  bXlzZWN1cmVwYXNzd29yZA==   # POSTGRES_PASSWORD
  POSTGRES_DB: bXlkYXRhYmFzZQ==      # POSTGRES_DB
