apiVersion: v1
kind: Pod
metadata:
  name: prefrence-affinity
  namespace: default
spec:
  containers:
  - name: pa-pod
    image: nginx:latest
    ports:
    - containerPort: 80 
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: "ENV"
            operator: In
            values:
            - dev

