apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-ns-limit
  namespace: prod-ns 
spec:
  hard:
    pods: "10"
    requests.cpu: "1"
    requests.memory: "1"
    limits.cpu: "2"
    limits.memory: "2"
