apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-deploy
  labels:
    env: dev

spec:
  replicas: 2
  template:
    metadata:
      name: rc-deploy
      labels:
        env: dev
    spec:
      containers:
      - name: rc-container
        image: nginx:latest
        ports:
        - containerPort: 80
  
