apiVersion: v1
kind: Pod
metadata:
  name: readiness
  namespace: default
spec:
  containers:
  - name: shopping-pod
    image: amansingh12/shopping_page:latest
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "500m"
        memory: "500Mi"
      requests:
        cpu: "200m"
        memory: "256Mi"
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 3
      failureThreshold: 3
