apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: default
spec:
  containers:
  - name: mysql-pod
    image: mysql:5.7
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "Test@123"
    resources:
      limits:
        cpu: "500m"
        memory: "500Mi"
      requests:
        cpu: "200m"
        memory: "256Mi"
    readinessProbe:
      exec:
        command:
        - sh
        - -c
        - mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD
      initialDelaySeconds: 15
      periodSeconds: 3
      timeoutSeconds: 1
      failureThreshold: 3

