apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-deploy
  labels:
    app: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: rs-deploy
        image: nginx
        ports:
        - containerPort: 80
