apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aman-rolebinding
  namespace: default
subjects:
- kind: User
  name: aman
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: aman-read-role
  apiGroup: rbac.authorization.k8s.io

